server:
  http_listen_port: 9080   # порт Promtail API
  grpc_listen_port: 0      # gRPC отключен

positions:
  filename: /tmp/positions.yaml  # где хранится прогресс
#    чтения логов

clients:
  - url: http://loki:3100/loki/api/v1/push  # адрес Loki

scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets:
            # путь к приложению, запущенному локально
            - host.docker.internal
        labels:
          job: fastapi
          # путь к логам приложения (volume должен быть смонтирован)
          __path__: /logs/*.json
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            msg: message
            logger: name
      - labels:
          level:
          logger:
